TravelBus/Controllers/HomeController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using X.PagedList;

namespace TravelBus.Controllers
{
    public class HomeController : Controller
    {
        PlaceManager placeManager = new PlaceManager(new PlaceRepositoryEF());
        SubscribeManager subscribeManager = new SubscribeManager(new SubscribeRepositoryEF());

        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public PartialViewResult Subscribe()
        {
            return PartialView();
        }
        [HttpPost]
        public IActionResult Subscribe(Subscribe sm)
        {
            SubscribeValidator subscribeValidator = new SubscribeValidator();
            ValidationResult result = subscribeValidator.Validate(sm);
            if (result.IsValid)
            {
                subscribeManager.TAdd(sm);
                return RedirectToAction("Index");
            }
            else
            {
                foreach(var item in result.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
                return View();
            }
        }
    }
}

TravelBus/ViewComponents/BestPlacesViewComponent.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using X.PagedList;
using X.PagedList.Mvc.Core;

namespace TravelBus.ViewComponents
{
    public class BestPlacesViewComponent : ViewComponent
    {
        PlaceManager placeManager = new PlaceManager(new PlaceRepositoryEF());
        public IViewComponentResult Invoke()
        {
            var values = placeManager.GetPlaceWithCountry().OrderByDescending(z => z.PlaceID).Take(6);
            return View(values);
        }
    }
}

TravelBus/ViewComponents/CategoriesBoxViewComponent.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TravelBus.ViewComponents
{
    public class CategoriesBoxViewComponent : ViewComponent
    {
        CountryManager countryManager = new CountryManager(new CountryRepositoryEF());
        public IViewComponentResult Invoke()
        {
            var values = countryManager.GetList().Take(3);
            return View(values);
        }
    }
}

TravelBus/ViewComponents/MeetTheTeamViewComponent.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TravelBus.ViewComponents
{
    public class MeetTheTeamViewComponent : ViewComponent
    {
        PlaceManager placeManager = new PlaceManager(new PlaceRepositoryEF());
        public IViewComponentResult Invoke()
        {
            var values = placeManager.GetPlaceWithCountry().OrderByDescending(z => z.PlaceID).Take(3);
            return View(values);
        }
    }
}

TravelBus/ViewComponents/SwipperViewComponent.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TravelBus.ViewComponents
{
    public class SwipperViewComponent : ViewComponent
    {
        PlaceManager placeManager = new PlaceManager(new PlaceRepositoryEF());
        public IViewComponentResult Invoke()
        {
            var values = placeManager.GetPlaceWithCountry().OrderByDescending(z => z.PlaceID).Take(3);
            return View(values);
        }
    }
}

TravelBus/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@await Component.InvokeAsync("Swipper")
@await Component.InvokeAsync("CategoriesBox")
@await Component.InvokeAsync("BestPlaces")
@await Component.InvokeAsync("MeetTheTeam")
@await Html.PartialAsync("Subscribe")

TravelBus/Views/Home/Subscribe.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@model EntityLayer.Concrete.Subscribe
<!-- Section Subscribe-->
<section class="section bg-gray-4 text-center offset-top-50">
    <div class="parallax-container" data-parallax-img="https://blog.mystart.com/wp-content/uploads/shutterstock_330839996-e1523646795412.jpg">
        <div class="parallax-content section-xl section-inset-custom-1 context-dark bg-overlay-2-21">
            <div class="container">
                <h2 class="heading-2 oh font-weight-normal wow slideInDown"><span class="d-block font-weight-semi-bold">First-class Impressions</span><span class="d-block font-weight-light">are Waiting for You!</span></h2>
                <p class="text-width-medium text-spacing-75 wow fadeInLeft" data-wow-delay=".1s">Our agency offers travelers various tours and excursions with destinations all over the world. Browse our website to find your dream tour!</p>
                <br />
                @using (Html.BeginForm("Subscribe", "Home", FormMethod.Post))
                {
                    <div class="form-group row">
                        <div class="col-lg-4" style="">
                        </div>
                        <div class="col-lg-4" style="">
                            @Html.TextBoxFor(x=>x.SubscribeMail,new { @class="form-control form-control-lg ", @placeholder = "Enter your email address", @type = "email" })
                            @Html.ValidationMessageFor(x=>x.SubscribeMail,"",new { @style= "color:#fff200" })
                        </div>
                    </div>
                        <button type="submit" id="btn" class="button button-secondary button-pipaluk">Subscribe</button>
                }
            </div>
        </div>
    </div>
</section>

@*<script type="text/javascript">
    $("#btn").click(function () {
        let values = {
            SubscribeMail: $("#txtmail").val()
        };

        $.ajax({
            type: "post",
            url: "/Home/Subscribe/",
            data=values,
            success: function (func) {
                let result = jQuery.parseJSON(func);
            }
        });
    });
</script>
<script src="~/js/jquery-3.3.1.min.js" type="text/javascript" ></script>*@