TravelBus/Controllers/PlaceController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Xml.Linq;
using X.PagedList;

namespace TravelBus.Controllers
{
    public class PlaceController : Controller
    {
        PlaceManager placeManager = new PlaceManager(new PlaceRepositoryEF());
        Place place;

        public IActionResult PlaceDetails(int id)
        {
            ViewBag.i = id;
            place = placeManager.GetByID(id);
            string city = place.CityName;
            var values = placeManager.GetPlaceByID(id);
            string api = "0b665c031af8b88018c6b10cfd28bc09";
            string link1 = "https://api.openweathermap.org/data/2.5/weather?q=";
            string link2 = "&mode=xml&units=metric&appid=";
            string connection= link1+city+link2+api;
            XDocument document = XDocument.Load(connection);
            ViewBag.weather = document.Descendants("temperature").ElementAt(0).Attribute("value").Value;
            return View(values);
        }

        public IActionResult ListAllPlaces(int id,int page=1)
        {
            var values = placeManager.GetPlaceByCountry(id).OrderByDescending(z => z.PlaceID).ToPagedList(page, 9);
            return View(values);
        }
    }
}

TravelBus/ViewComponents/CommentViewComponent.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TravelBus.ViewComponents
{
    public class CommentViewComponent :  ViewComponent
    {
        CommentManager commentManager = new CommentManager(new CommentRepositoryEF());
        public IViewComponentResult Invoke(int id)
        {
            var values = commentManager.GetList(id);
            return View(values);
        }
    }
}

TravelBus/ViewComponents/ContentsByIdViewComponent.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TravelBus.ViewComponents
{
    public class ContentsByIdViewComponent : ViewComponent
    {
        ContentManager contentManager = new ContentManager(new ContentRepositoryEF());
        public IViewComponentResult Invoke(int id)
        {
            var values = contentManager.GetList(id);
            return View(values);
        }
    }
}

TravelBus/ViewComponents/ImagesInDetailViewComponent.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TravelBus.ViewComponents
{
    public class ImagesInDetailViewComponent :ViewComponent
    {
        ImageManager imageManager = new ImageManager(new ImageRepositoryEF());
        public IViewComponentResult Invoke(int id)
        {
            var values = imageManager.GetList(id);    
            return View(values);
        }
    }
}

TravelBus/Views/Place/ListAllPlaces.cshtml
@using X.PagedList
@using X.PagedList.Mvc.Core
@using X.PagedList.Web.Common;

@model IPagedList<EntityLayer.Concrete.Place>
@{
    ViewData["Title"] = "ListAllPlaces";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/MaterialDesign-Webfont/5.3.45/css/materialdesignicons.css" integrity="sha256-NAxhqDvtY0l4xn+YVa6WjAcmd94NNfttjNsDmNatFVc=" crossorigin="anonymous" />
<link href="~/css/BlogList.css" rel="stylesheet" />
    <div class="page">
        <!-- Breadcrumbs -->
        <section class="breadcrumbs-custom-inset">
            <div class="breadcrumbs-custom context-dark bg-overlay-60">
                <div class="container">
                    <h2 class="breadcrumbs-custom-title">About</h2>
                    <ul class="breadcrumbs-custom-path">
                        <li><a href="index.html">Home</a></li>
                        <li class="active">About</li>
                    </ul>
                </div>
                <div class="box-position" style="background-image: url(https://www.desktopbackground.org/download/o/2011/08/23/254359_ocean-views-wallpapers-wallpapers-cave_1920x1080_h.jpg);"></div>
            </div>
        </section>
        <section class="section section-sm section-first bg-default section-md section-xl section-lg section-xs">
            <div class="container">
                <h3>Best Destinations</h3>
                <div class="row row-30">
                    <div class="row">
                        @foreach (var x in Model)
                        {
                            <div class="col-lg-4 col-md-6 mt-4 pt-2">
                                <div class="blog-post rounded border">
                                    <div class="blog-img d-block overflow-hidden position-relative">
                                        <img src="@x.LocationUrl" class="img-fluid rounded-top">
                                        <div class="overlay rounded-top bg-dark"></div>
                                        <div class="post-meta">
                                            <a href="/Place/PlaceDetails/@x.PlaceID/" class="text-light read-more">Read More <i class="mdi mdi-chevron-right"></i></a>
                                        </div>
                                    </div>
                                    <div class="content p-3">
                                        <small class="text-muted p float-right">@(((DateTime)x.CreatedDate).ToString("dd-MMMM-yyyy"))</small>
                                        <small><a href="javascript:void(0)" class="text-primary"></a></small>
                                        <h4 class="mt-2"><a href="/Place/PlaceDetails/@x.PlaceID/" class="text-dark title">@x.PlaceName</a></h4>
                                        <p class="text-muted mt-2">Explore the @x.PlaceName in @x.CityName...</p>
                                    </div>
                                </div><!--end blog post-->
                            </div><!--end col-->
                        }
                    </div><!--end row-->
                </div>
            </div>
            <br />
            @Html.PagedListPager((IPagedList)Model, page => Url.Action("ListAllPlaces", new { page }), new PagedListRenderOptions
                   {
                            DisplayLinkToIndividualPages = true,
                            DisplayPageCountAndCurrentLocation = true,
                            LiElementClasses = new string[] { "page-item" },
                       PageClasses = new string[] { "page-link" },

    })
        </section>
    </div><!--end row-->

TravelBus/Views/Place/PlaceDetails.cshtml
@model IEnumerable<EntityLayer.Concrete.Place>
@{
    ViewData["Title"] = "PlaceDetails";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="~/css/PlaceDetails.css" rel="stylesheet" />
<div class="blog-single gray-bg">
    <div class="container">
        <div class="row align-items-start">
            <div class="col-lg-8 m-15px-tb">
                @foreach (var x in Model)
                {
                    <article class="article">

                        <div class="article-img">
                            <img src="@x.LocationUrl" title="" alt="">
                        </div>
                        <div class="article-title">
                            <h2>@x.PlaceName</h2>
                            <h6 style="text-align:center">@x.CityName</h6>

                            @*<div class="media">
                        <div class="media-body">
                            <label>Rachel Roth</label>
                            <span>@x.CreatedDate</span>
                        </div>
                    </div>*@

                        </div>
                        @await Component.InvokeAsync("ContentsById", new { id = ViewBag.i })
                    </article>
                }
                @await Component.InvokeAsync("Comment", new { id = ViewBag.i })
                @await Html.PartialAsync("/Views/Comment/AddComment.cshtml")
            </div>
            <div class="col-lg-4 m-15px-tb blog-aside">
                <!-- Author -->
                <div class="widget widget-author">
                    <div class="widget-title">
                        <h3>Author</h3>
                    </div>
                    <div class="widget-body">
                        <div class="media align-items-center">
                            <div class="avatar">
                                <img src="https://bootdey.com/img/Content/avatar/avatar6.png" title="" alt="">
                            </div>
                            <div class="media-body">
                                <h6>Hello, I'm<br> Rachel Roth</h6>
                            </div>
                        </div>
                        <p>I design and develop services for customers of all sizes, specializing in creating stylish, modern websites, web services and online stores</p>
                    </div>
                </div>
                <!-- End Author -->
                <!-- Location -->
                <div class="widget widget-post">
                    <div class="widget-title">
                        <h3>Location</h3>
                    </div>
                    @foreach (var x in Model)
                    {
                        <div class="widget-body">
                            <iframe src="@x.LocationUrl" width="100%" height="450" style="border:0;" allowfullscreen="" loading="lazy"></iframe>

                        </div>
                    }
                </div>

                <div class="widget widget-post">
                    <div class="widget-title">
                        <h3>Weather</h3>
                    </div>
                    @foreach (var x in Model)
                    {
                        <div class="widget-body">
                            <div>
                               <i class="fa fa-cloud fa-5x"></i>
                            </div>
                            <h4 class="font-bold">@x.CityName</h4>
                            <br />
                            <h6 class="font-bold">@ViewBag.weather 'C</h6>
                        </div>
                    }
                </div>


                <!-- End Location -->
                <!-- Latest Post -->
                <div class="widget widget-latest-post">
                    <div class="widget-title">
                        <h3>Latest Post</h3>
                    </div>
                    <div class="widget-body">
                        <div class="latest-post-aside media">
                            <div class="lpa-left media-body">
                                <div class="lpa-title">
                                    <h5><a href="#">Prevent 75% of visitors from google analytics</a></h5>
                                </div>
                                <div class="lpa-meta">
                                    <a class="name" href="#">
                                        Rachel Roth
                                    </a>
                                    <a class="date" href="#">
                                        26 FEB 2020
                                    </a>
                                </div>
                            </div>
                            <div class="lpa-right">
                                <a href="#">
                                    <img src="https://via.placeholder.com/400x200/FFB6C1/000000" title="" alt="">
                                </a>
                            </div>
                        </div>
                        <div class="latest-post-aside media">
                            <div class="lpa-left media-body">
                                <div class="lpa-title">
                                    <h5><a href="#">Prevent 75% of visitors from google analytics</a></h5>
                                </div>
                                <div class="lpa-meta">
                                    <a class="name" href="#">
                                        Rachel Roth
                                    </a>
                                    <a class="date" href="#">
                                        26 FEB 2020
                                    </a>
                                </div>
                            </div>
                            <div class="lpa-right">
                                <a href="#">
                                    <img src="https://via.placeholder.com/400x200/FFB6C1/000000" title="" alt="">
                                </a>
                            </div>
                        </div>
                        <div class="latest-post-aside media">
                            <div class="lpa-left media-body">
                                <div class="lpa-title">
                                    <h5><a href="#">Prevent 75% of visitors from google analytics</a></h5>
                                </div>
                                <div class="lpa-meta">
                                    <a class="name" href="#">
                                        Rachel Roth
                                    </a>
                                    <a class="date" href="#">
                                        26 FEB 2020
                                    </a>
                                </div>
                            </div>
                            <div class="lpa-right">
                                <a href="#">
                                    <img src="https://via.placeholder.com/400x200/FFB6C1/000000" title="" alt="">
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- End Latest Post -->
            </div>
        </div>
    </div>
</div>
@await Component.InvokeAsync("ImagesInDetail", new { id = ViewBag.i })